project:
  type: website
  output-dir: docs

website:
  title: "Clarice S Groeneveld"
  description: "Bioinformatics and data visualization blog"
  navbar:
    background: "#0f986b"
    foreground: "#ffffff"
    right:
      - index.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/csgroen
      - icon: twitter
        href: https://twitter.com/cs_groen
format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css

editor: visual

