project:
  type: website
  output-dir: docs

website:
  title: "Blog | Clarice S Groeneveld"
  description: "Bioinformatics and data visualization blog"
  navbar:
    background: "#2ec4b6"
    foreground: "#ffffff"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/csgroen
      - icon: twitter
        href: https://twitter.com/cs_groen
format:
  html:
    theme: journal
    css: styles.css

editor: visual

